---
# tasks file for update-rules
  - name: Update rule file to Prometheus
    command:
      python3 converter.py
    register: result

  - name: clone rule file into destination
    command:
      cp ../deploy-service/docker/prometheus/gb200_rules.yml {{ rule_path }}
    become: true