---
# Step 1: Check Internet and Ansible version.
- name: Verify Internet Connection
  hosts: localhost
  connection: local
  tasks:  

  - name: Check Internet connectivity
    shell: ping -c 1 8.8.8.8
    register: internet_status
    failed_when: internet_status.rc != 0

  - name: Fail if no Internet connection
    fail:
      msg: "No Internet connection detected. Please check your network."
    when: internet_status is failed

- name: Check Ansible Version
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Get Ansible version
      debug:
        msg: "Ansible version is newer than 2.10"
      when: ansible_version.full is version('2.10', '>=')

    - name: Notify if Ansible version is 2.10 or older
      fail:
        msg: "Ansible version is 2.10 or older"
      when: ansible_version.full is version('2.10', '<')

# Step 2: Install python required dependencies
- name: install python required dependencies
  hosts: local
  connection: local
  become: true
  tasks:
    - name: install pip 
      apt: 
        name: python3-pip
    
    - name: install dependencies from requirement file
      become: false
      command:
        cmd: pip install -r deploy/requirements.txt

# Step 3: generate rule_file
- name: Deployment configuration
  hosts: local
  connection: local
  tasks:

  - name: Update rule file to Prometheus
    command:
      python3 feature/converter.py
    register: result

# Step 4: Check required services
- name: check existance of required services
  hosts: local
  connection: local
  become: true

  tasks:

  - name: check docker existing 
    shell: docker ps --format "{{'{{.Names}}'}}" | grep {{ item }}
    loop: 
      - prometheus
      - alertmanager
      - grafana
    register: docker_name_result
    ignore_errors: true

  - name: Check the count of missing containers
    set_fact:
      missing_containers: >-
        {{ docker_name_result.results | selectattr('rc', 'ne', 0) | map(attribute='item') | list }}

  - name: Fail if some but not all containers are missing
    fail:
      msg: >-
        The following containers are missing: {{ missing_containers | join(', ') }}
        either close all prometheus, alertmanager and grafana to auto-download from this deployment
        or manually download them via docker image
    when: >
      missing_containers | length > 0 and missing_containers | length < 3

  - name: Run docker playbook if all containers are missing
    ansible.builtin.include_tasks: deploy/deploy_docker.yml
    when: "{{ missing_containers | length == 3 }}"
  
  - name: Run append playbook if all containers are present
    ansible.builtin.include_tasks: deploy/append_config.yml
    when: "{{ missing_containers | length == 0 }}"

# Step 5: Check required services
- name: Open line and control webhook service
  hosts: local
  connection: local
  become: true

  tasks:

  - name: Build docker images
    command:
      cmd: docker build -t code-docker .
  
  - name: open up code-docker
    command:
      cmd: docker run -d --name webhook-container -p 5100:5100 -p 5200:5200 code-docker
