---
- name: Deployment playbook
  hosts: localhost
  tasks:

  - name: Gather target information from inventory
    set_fact:
      ips: "{{ ( groups['local'] + groups['targets'] ) | map('extract', hostvars, 'ansible_host') | list }}"

  - name: Generate Prometheus configuration file
    template:
      src: docker/prometheus/prometheus.yml.j2
      dest: docker/prometheus/prometheus.yml
    vars:
      host_ip: "{{ ips[0] }}"
      target1_ip: "{{ ips[1] }}"
      target2_ip: "{{ ips[2] }}"

  - name: Generate alertmanager configuration file
    template:
      src: docker/alertmanager/alertmanager.yml.j2
      dest: docker/alertmanager/alertmanager.yml
    vars:
      webhook_ip: "{{ ips[0] }}"

  - name: Update rule file to Prometheus
    command:
      python3 temp/config/converter.py
    register: result
  
  - name: Find the pid of Prometheus
    shell: |
      ps -aux | grep prometheus | awk '{print $2}' | head -n 1
    register: prometheus_pid
    ignore_errors: yes

  - name: kill the pid to update rule in prometheus
    shell: |
      kill -HUP {{ prometheus_pid.stdout }}
    become: yes
    ignore_errors: yes






  