---
- name: Deployment playbook
  hosts: localhost
  tasks:

  - name: Update rule file to Prometheus
    command:
      python3 feature/converter.py
    register: result

  - name: Get prometheus docker container's name
    shell: docker ps --format "{{'{{.Names}}'}}" | grep prometheus
    register: running_container_name
    become: true
    
  - name: restart prometheus service
    shell: docker exec {{ running_container_name.stdout }} kill -s SIGHUP 1
    become: true
