---
# groups 1, handle HostHighCpuLoad
- name: Automate CPU high usage monitoring and kill process
  hosts: "{{ COMPUTE_NODE }}"
  tags: HeavyCpuUsage
  tasks:

    - name: Ask who am i
      ansible.builtin.shell: whoami
      register: result
    
    - name: Debug result
      debug:
        msg: "{{ result.stdout }}"

    - name: Debug process_name
      debug:
        msg: "{{ PROCESS_NAME }}"


    - name: Find process ID by name
      ansible.builtin.shell: ps -e -o pid,comm | grep -w "{{ PROCESS_NAME }}" | awk '{print $1}'
      register: process_pid
      ignore_errors: yes

    - name: Debug process id output
      debug:
        msg: "{{ process_pid.stdout }}"


    - name: Kill the process if it is running
      ansible.builtin.shell: "kill -9 {{ item }}"
      loop: "{{ process_pid.stdout_lines }}"
      when: process_pid.stdout_lines | length > 0
      ignore_errors: yes



