version: '3.8'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: always
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    restart: always
    ports:
     - '9093:9093'
    volumes:
      - ./alertmanager:/etc/alertmanager
volumes:
  prom_data:
  grafana-storage: {}
