groups:
- name: GPU Metrics
  rules:
  - alert: GPUPowerTotal_Critical
    annotations:
      description: The total power usage of the GPU has surpassed the recommended
        threshold, indicating potential overuse or overheating.
      summary: High GPU power consumption detected.
    expr: sum(DCGM_FI_DEV_POWER_USAGE{instance="hgx3b:9400"}) > 2200
    for: 15s
    labels:
      severity: Critical
  - alert: GPUPowerTotal_Warning
    annotations:
      description: The total power usage of the GPU has surpassed the recommended
        threshold, indicating potential overuse or overheating.
      summary: High GPU power consumption detected.
    expr: sum(DCGM_FI_DEV_POWER_USAGE{instance="hgx3b:9400"}) < 2200 and sum(DCGM_FI_DEV_POWER_USAGE{instance="hgx3b:9400"})
      > 1800
    for: 15s
    labels:
      severity: Warning
  - alert: GPUAvgTemp_Critical
    annotations:
      description: The average temperature of the GPU has exceeded safe operating
        limits, suggesting potential cooling issues or heavy load.
      summary: High average GPU temperature detected.
    expr: avg(DCGM_FI_DEV_GPU_TEMP{instance="hgx3b:9400"}) > 87
    for: 15s
    labels:
      severity: Critical
  - alert: GPUAvgTemp_Warning
    annotations:
      description: The average temperature of the GPU has exceeded safe operating
        limits, suggesting potential cooling issues or heavy load.
      summary: High average GPU temperature detected.
    expr: avg(DCGM_FI_DEV_GPU_TEMP{instance="hgx3b:9400"}) < 87 and avg(DCGM_FI_DEV_GPU_TEMP{instance="hgx3b:9400"})
      > 83
    for: 15s
    labels:
      severity: Warning
  - alert: GPUTotalUtilization_Critical
    annotations:
      description: The total utilization of the GPU is too high, which could lead
        to performance degradation or overheating.
      summary: High GPU utilization detected.
    expr: avg(DCGM_FI_DEV_GPU_UTIL{instance="hgx3b:9400"}) > 0.9
    for: 15s
    labels:
      severity: Critical
  - alert: GPUTotalUtilization_Warning
    annotations:
      description: The total utilization of the GPU is too high, which could lead
        to performance degradation or overheating.
      summary: High GPU utilization detected.
    expr: avg(DCGM_FI_DEV_GPU_UTIL{instance="hgx3b:9400"}) < 0.9 and avg(DCGM_FI_DEV_GPU_UTIL{instance="hgx3b:9400"})
      > 0.8
    for: 15s
    labels:
      severity: Warning
  - alert: GPUAvgMemCpyUtilization_Critical
    annotations:
      description: The average memory copy utilization is too high, potentially affecting
        GPU performance and memory bandwidth.
      summary: High average GPU memory copy utilization.
    expr: avg(DCGM_FI_DEV_MEM_COPY_UTIL{instance="hgx3b:9400"}) > 90
    for: 15s
    labels:
      severity: Critical
  - alert: GPUAvgMemCpyUtilization_Warning
    annotations:
      description: The average memory copy utilization is too high, potentially affecting
        GPU performance and memory bandwidth.
      summary: High average GPU memory copy utilization.
    expr: avg(DCGM_FI_DEV_MEM_COPY_UTIL{instance="hgx3b:9400"}) < 90 and avg(DCGM_FI_DEV_MEM_COPY_UTIL{instance="hgx3b:9400"})
      > 70
    for: 15s
    labels:
      severity: Warning
  - alert: GPUPowerUsage_Critical
    annotations:
      description: The power usage of the GPU is higher than expected, which could
        be indicative of inefficient workload or hardware issues.
      summary: Excessive GPU power usage detected.
    expr: DCGM_FI_DEV_POWER_USAGE{instance="hgx3b:9400"} > 275
    for: 15s
    labels:
      severity: Critical
  - alert: GPUPowerUsage_Warning
    annotations:
      description: The power usage of the GPU is higher than expected, which could
        be indicative of inefficient workload or hardware issues.
      summary: Excessive GPU power usage detected.
    expr: DCGM_FI_DEV_POWER_USAGE{instance="hgx3b:9400"} < 275 and DCGM_FI_DEV_POWER_USAGE{instance="hgx3b:9400"}
      > 225
    for: 15s
    labels:
      severity: Warning
  - alert: GPUTemperature_Critical
    annotations:
      description: The GPU temperature has exceeded the threshold, risking thermal
        throttling or damage to the hardware.
      summary: High GPU temperature detected.
    expr: DCGM_FI_DEV_GPU_TEMP{instance="hgx3b:9400"} > 87
    for: 15s
    labels:
      severity: Critical
  - alert: GPUTemperature_Warning
    annotations:
      description: The GPU temperature has exceeded the threshold, risking thermal
        throttling or damage to the hardware.
      summary: High GPU temperature detected.
    expr: DCGM_FI_DEV_GPU_TEMP{instance="hgx3b:9400"} < 87 and DCGM_FI_DEV_GPU_TEMP{instance="hgx3b:9400"}
      > 83
    for: 15s
    labels:
      severity: Warning
  - alert: GPUUtilization_Critical
    annotations:
      description: The GPU is being utilized beyond recommended levels, which may
        result in overheating or reduced lifespan.
      summary: High GPU utilization detected.
    expr: DCGM_FI_DEV_GPU_UTIL{instance="hgx3b:9400"} > 0.9
    for: 15s
    labels:
      severity: Critical
  - alert: GPUUtilization_Warning
    annotations:
      description: The GPU is being utilized beyond recommended levels, which may
        result in overheating or reduced lifespan.
      summary: High GPU utilization detected.
    expr: DCGM_FI_DEV_GPU_UTIL{instance="hgx3b:9400"} < 0.9 and DCGM_FI_DEV_GPU_UTIL{instance="hgx3b:9400"}
      > 0.8
    for: 15s
    labels:
      severity: Warning
  - alert: GPUMemCpyUtilization_Critical
    annotations:
      description: The memory copy utilization of the GPU is too high, indicating
        potential memory bottlenecks or inefficient workload distribution.
      summary: High GPU memory copy utilization detected.
    expr: DCGM_FI_DEV_MEM_COPY_UTIL{instance="hgx3b:9400"} > 90
    for: 15s
    labels:
      severity: Critical
  - alert: GPUMemCpyUtilization_Warning
    annotations:
      description: The memory copy utilization of the GPU is too high, indicating
        potential memory bottlenecks or inefficient workload distribution.
      summary: High GPU memory copy utilization detected.
    expr: DCGM_FI_DEV_MEM_COPY_UTIL{instance="hgx3b:9400"} < 90 and DCGM_FI_DEV_MEM_COPY_UTIL{instance="hgx3b:9400"}
      > 70
    for: 15s
    labels:
      severity: Warning
  - alert: GPUMemUsage_Critical
    annotations:
      description: The memory usage on the GPU has reached critical levels, which
        could cause instability or performance issues.
      summary: High GPU memory usage detected.
    expr: DCGM_FI_DEV_FB_USED{instance="hgx3b:9400"}/(DCGM_FI_DEV_FB_USED{instance="hgx3b:9400"}+DCGM_FI_DEV_FB_FREE{instance="hgx3b:9400"})
      > 90
    for: 15s
    labels:
      severity: Critical
  - alert: GPUMemUsage_Warning
    annotations:
      description: The memory usage on the GPU has reached critical levels, which
        could cause instability or performance issues.
      summary: High GPU memory usage detected.
    expr: DCGM_FI_DEV_FB_USED{instance="hgx3b:9400"}/(DCGM_FI_DEV_FB_USED{instance="hgx3b:9400"}+DCGM_FI_DEV_FB_FREE{instance="hgx3b:9400"})
      < 90 and DCGM_FI_DEV_FB_USED{instance="hgx3b:9400"}/(DCGM_FI_DEV_FB_USED{instance="hgx3b:9400"}+DCGM_FI_DEV_FB_FREE{instance="hgx3b:9400"})
      > 70
    for: 15s
    labels:
      severity: Warning
  - alert: GPUXIDError_Critical
    annotations:
      description: nan
      summary: nan
    expr: DCGM_FI_DEV_XID_ERRORS != 0
    for: 15s
    labels:
      severity: Critical
- name: System Metrics
  rules:
  - alert: PrometheusJobMissing_Warning
    annotations:
      description: A Prometheus job has disappeared\n  VALUE = {{ $value }}\n  LABELS
        = {{ $labels }}
      summary: Prometheus job missing (instance {{ $labels.instance }})
    expr: absent(up{job="prometheus"})
    for: 0m
    labels:
      severity: Warning
