---
galaxy_info:
  role_name: restart_docker_service
  author: Eason Chang
  description: "Ansible role to restart a service inside a Docker container"
  company: FOXCONN
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: RedHat
      versions:
        - 8
        - 9
  categories:
    - docker
    - system
dependencies: []
